// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzzqqtzfrskdgufplcvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6enFxdHpmcnNrZGd1ZnBsY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTk0MzAsImV4cCI6MjA2MzUzNTQzMH0.XI2OwCWMGos0Pv9ss_NafcRCm_aHxTfQxvkiZGrHnPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);